---
title: "Individual Sampling"
output: pdf_document
---

```{r}
source('setup.R')
```

## Rho = 0 (ZERO COVARIANCE)
```{r}
nsims = 1000
set.seed(98)
kvec = c(250,500,750,1000,1250,1500,1750,2000,2250,2500,3000,3500,4000,4500,5000)

agg0.indiv.biases.k = createlist(length(kvec),nsims,length(coeffs))

for (i in 1:nsims){
sim = simfunc(mean1 = rnorm(n.counties, mean = 1, sd = 0.1), mean2 = rnorm(n.counties, mean = 1, sd = 0.1), N = 100, mu = rep(0.05, n.counties), alpha = 1, beta = 2, rho = 0)

aggdata <- as.data.frame(cbind(y=sim$y, airpollution = sim$group.airpollution, income = sim$group.income))

indivdata <- as.data.frame(cbind(y = sim$case, airpollution = sim$indiv.airpollution, income = sim$indiv.income))
  
for (j in 1:length(kvec)){
  k = kvec[j]
  indivdata.new <- indivdata[sample(nrow(indivdata), k), ]

  #Fit model on aggregate and individual data
  agg.indiv.eco <- eco(cbind(y, N) ~ 1, normal = ~airpollution + income, iformula = y ~ airpollution + income, data = aggdata, idata=indivdata.new)

  agg0.indiv.biases.k[[j]][i,] = log(c(agg.indiv.eco$ors.ctx[,1],agg.indiv.eco$ors.indiv[,1])) - coeffs
  }
}
```

## Rho = 1 (HIGH POSITIVE COVARIANCE)
```{r}
agg1.indiv.biases.k = createlist(length(kvec),nsims,length(coeffs))

for (i in 1:nsims){
  sim = simfunc(mean1 = rnorm(n.counties, mean = 1, sd = 0.1), mean2 = rnorm(n.counties, mean = 1, sd = 0.1), N = 100, mu = rep(0.05, n.counties), alpha = 1, beta = 2, rho = 1)

  aggdata <- as.data.frame(cbind(y=sim$y, airpollution = sim$group.airpollution, income = sim$group.income))

  indivdata <- as.data.frame(cbind(y = sim$case, airpollution = sim$indiv.airpollution, income = sim$indiv.income))
  
for (j in 1:length(kvec)){
  k = kvec[j]
  indivdata.new <- indivdata[sample(nrow(indivdata), k), ]

  #Fit model on aggregate and individual data
  agg.indiv.eco <- eco(cbind(y, N) ~ 1, normal = ~airpollution + income, iformula = y ~ airpollution + income, data = aggdata, idata=indivdata.new)

  agg1.indiv.biases.k[[j]][i,] = log(c(agg.indiv.eco$ors.ctx[,1],agg.indiv.eco$ors.indiv[,1])) - coeffs
  }
}
```

## Rho = -1 (HIGH POSITIVE COVARIANCE)
```{r}
aggneg1.indiv.biases.k = createlist(length(kvec),nsims,length(coeffs))

for (i in 1:nsims){
  sim = simfunc(mean1 = rnorm(n.counties, mean = 1, sd = 0.1), mean2 = rnorm(n.counties, mean = 1, sd = 0.1), N = 100, mu = rep(0.05, n.counties), alpha = 1, beta = 2, rho = -1)

  aggdata <- as.data.frame(cbind(y=sim$y, airpollution = sim$group.airpollution, income = sim$group.income))

  indivdata <- as.data.frame(cbind(y = sim$case, airpollution = sim$indiv.airpollution, income = sim$indiv.income))
  
for (j in 1:length(kvec)){
  k = kvec[j]
  indivdata.new <- indivdata[sample(nrow(indivdata), k), ]

  #Fit model on aggregate and individual data
  agg.indiv.eco <- eco(cbind(y, N) ~ 1, normal = ~airpollution + income, iformula = y ~ airpollution + income, data = aggdata, idata=indivdata.new)

  aggneg1.indiv.biases.k[[j]][i,] = log(c(agg.indiv.eco$ors.ctx[,1],agg.indiv.eco$ors.indiv[,1])) - coeffs
  }
}
```

## Plots
```{r}
mu.agg.indiv.k0 = bindmeans(agg0.indiv.biases.k, 1)
alpha.agg.indiv.k0 = bindmeans(agg0.indiv.biases.k, 2)
beta.agg.indiv.k0 = bindmeans(agg0.indiv.biases.k, 3)

mu.agg.indiv.k1 = bindmeans(agg1.indiv.biases.k, 1)
alpha.agg.indiv.k1 = bindmeans(agg1.indiv.biases.k, 2)
beta.agg.indiv.k1 = bindmeans(agg1.indiv.biases.k, 3)

mu.agg.indiv.kneg1 = bindmeans(aggneg1.indiv.biases.k, 1)
alpha.agg.indiv.kneg1 = bindmeans(aggneg1.indiv.biases.k, 2)
beta.agg.indiv.kneg1 = bindmeans(aggneg1.indiv.biases.k, 3)

##############
jpeg("mu.k.jpg", width = 500, height = 350)
plot(kvec, mu.agg.indiv.k0, type = 'l', ylab = 'bias', xlab = '# Individuals Sampled', ylim = c(-1,1), main = 'Bias of muhat', col = 'black', xaxt="n")
lines(kvec, mu.agg.indiv.k1, col = 'red')
lines(kvec,mu.agg.indiv.kneg1, col = 'blue')
axis(1, at = seq(0, 5000, by = 250))
legend("topright", legend=c("Rho = 0", "Rho = 1", "Rho = -1"),
       col=c("black", "red", "blue"), lty=c(1,1,1), cex=0.8)

jpeg("alpha.k.jpg", width = 500, height = 350)
plot(kvec, alpha.agg.indiv.k0, type = 'l', ylab = 'bias', xlab = '# Individuals Sampled', ylim = c(-1,1), main = 'Bias of alphahat', col = 'black', xaxt="n")
lines(kvec, alpha.agg.indiv.k1, col = 'red')
lines(kvec,mu.agg.indiv.kneg1, col = 'blue')
axis(1, at = seq(0, 5000, by = 250))
legend("topright", legend=c("Rho = 0", "Rho = 1", "Rho = -1"),
       col=c("black", "red", "blue"), lty=c(1,1,1), cex=0.8)

jpeg("beta.k.jpg", width = 500, height = 350)
plot(kvec, beta.agg.indiv.k0, type = 'l', ylab = 'bias', xlab = '# Individuals Sampled', ylim = c(-1,1), main = 'Bias of betahat', col = 'black', xaxt="n")
lines(kvec, beta.agg.indiv.k1, col = 'red')
lines(kvec,mu.agg.indiv.kneg1, col = 'blue')
axis(1, at = seq(0, 5000, by = 250))
legend("topright", legend=c("Rho = 0", "Rho = 1", "Rho = -1"),
       col=c("black", "red", "blue"), lty=c(1,1,1), cex=0.8)
```

